function setCookie(name,value,days){var date,expires;if(days){date=new Date();date.setTime(date.getTime()+(days*24*60*60*1000));expires="; expires="+date.toGMTString();}else{expires="";}
document.cookie=name+"="+value+expires+"; path=/";}
var YHDBookmark={"add":function(filmId){$.ajax({method:'GET',url:"/ajax/suggest",data:{Bookmark:true,filmId:filmId,type:"add"},dataType:'json',success:function(data){if(data.status==1){return true;}else{fx.alertMessage("Xin chào!","Bạn cần đăng nhập để sử dụng chức năng này!",'error');return false;}}});},"remove":function(filmId){$.ajax({method:'GET',url:"/ajax/notification",data:{Bookmark:true,filmId:filmId,type:"remove"},dataType:'json',success:function(data){if(data.status==1){return true;}else{fx.alertMessage("Xin chào!","Bạn cần đăng nhập để sử dụng chức năng này!",'error');return false;}}});},"handle":function(data){if(data.status==1)return true;else return false;},"checkBookmark":function(filmId){var result;$.get("/ajax/notification?Bookmark=true&filmId="+filmId,function(data){result=JSON.parse(data);if(result.status==1)return true;else return false;});},"load":function(){jQuery('#bookmark-box').css('display','block');if(jQuery('.tools-box-bookmark').length>0){jQuery('.tools-box-bookmark').each(function(){var filmId=jQuery(this).attr('data-filmid');if(typeof filmId=='string'){filmId=jQuery.trim(filmId);filmId=parseInt(filmId);if(!isNaN(filmId)&&filmId>0){$.get("/ajax/notification?Bookmark=true&filmId="+filmId,function(data){data=JSON.parse(data);if(data.status==1){jQuery(".tools-box-bookmark").addClass('added');jQuery(".tools-box-bookmark").removeClass('normal');jQuery(".tools-box-bookmark").attr('data-added','true');}else{jQuery(".tools-box-bookmark").addClass('normal');jQuery(".tools-box-bookmark").removeClass('added');jQuery(".tools-box-bookmark").attr('data-added','false');}});};jQuery(this).css('display','block');};})};}};function adBlockNotDetected(){$("div.top-message").css({"display":"none"});}
function adBlockDetected(){var isAdblock=true;if(isAdblock==true){$("div.top-message").html('<span>Xin vui lòng tắt chương trình chặn quảng cáo để chúng tôi có thể phục vụ bạn tốt hơn.</span>').css({"display":"block"});console.log("AdBlock: Enabled");}else{adBlockNotDetected();}}
function checkAdblock(){console.log("Call function FuckAdblock");if(typeof fuckAdBlock==='undefined'){adBlockDetected();}else{fuckAdBlock.setOption({debug:true});fuckAdBlock.onDetected(adBlockDetected).onNotDetected(adBlockNotDetected);}}
function loadNotif(){$.ajax({method:'GET',url:"/ajax/notification",data:{notif:true},dataType:'json',success:function(data){if(data.status==1){jQuery(".manage-notifi").html(data.html);if(data.total>0){jQuery(".navbar-notice-toggle").addClass("active");jQuery(".navbar-notice-toggle").html('<i class="fa fa-bell"></i> &nbsp;'+data.total);}else jQuery(".navbar-notice-toggle").html('<i class="fa fa-bell"></i>');}}});return false;}
jQuery(document).ready(function(t){var fixKeyword=function(str){str=str.toLowerCase();str=str.replace(/(<([^>]+)>)/gi,"");str=str.replace(/[`~!@#$%^&*()_|\=?;:'",.<>\{\}\[\]\\\/]/gi,"");str=str.split(" ").join("+");return str;}
jQuery('#form-search').submit(function(){var keywordObj=jQuery(this).find('input[name=keyword]')[0];if(typeof keywordObj!='undefined'&&keywordObj!=null){var keyword=jQuery(keywordObj).val();keyword=fixKeyword(keyword);keyword=jQuery.trim(keyword);if(keyword==''){alert('Bạn chưa nhập từ khóa. (Không tính các ký tự đặc biệt vào độ dài từ khóa)');jQuery(keywordObj).focus();return false;}
window.location.replace('/tim-kiem/'+keyword+'/');}
return false;});jQuery('#form-search1').submit(function(){var keywordObj=jQuery(this).find('input[name=keyword]')[0];if(typeof keywordObj!='undefined'&&keywordObj!=null){var keyword=jQuery(keywordObj).val();keyword=fixKeyword(keyword);keyword=jQuery.trim(keyword);if(keyword==''){alert('Bạn chưa nhập từ khóa. (Không tính các ký tự đặc biệt vào độ dài từ khóa)');jQuery(keywordObj).focus();return false;}
window.location.replace('/tim-kiem/'+keyword+'/');}
return false;});YHDBookmark.load();checkAdblock();$('div.Top').on('click','a.STPb',function(e){e.preventDefault();$this=$(this);var $parent=$this.parents("section").attr("id");var $tag=$this.data("tag");$('#'+$parent+' .Top a').removeClass("Current");$this.addClass("Current");var href=$this.attr("href");$("a.viewall").attr("href",href);$("#loading").css({"display":"block"});$.ajax({type:'POST',url:MAIN_URL+'/ajax/item',data:{widget:'list-film',type:$tag},success:function(html){$('#'+$parent+' ul.MovieList').html(html);$("#loading").css({"display":"none"});},error:function(){fx.alertMessage("Lỗi","Đã có lỗi xảy ra trong quá trình gửi dữ liệu!","error");}});});jQuery('.tools-box-bookmark').click(function(){var $this=jQuery('.tools-box-bookmark');var added=$this.attr('data-added');var filmId=$this.attr('data-filmid');if(typeof added=='string'&&added=='true'){added=true}else{added=false};if(added){$.ajax({method:'GET',url:"/ajax/notification",data:{Bookmark:true,filmId:filmId,type:"remove"},dataType:'json',success:function(data){if(data.status==1){$this.addClass('normal');$this.removeClass('added');$this.attr('data-added','false');fx.alertMessage("Bỏ theo dõi","Bạn đã bỏ theo dõi thành công phim này!",'error');}else{fx.alertMessage("Xin chào!","Bạn cần đăng nhập để sử dụng chức năng này!",'error');}}});}else{$.ajax({method:'GET',url:"/ajax/notification",data:{Bookmark:true,filmId:filmId,type:"add"},dataType:'json',success:function(data){if(data.status==1){$this.addClass('added');$this.removeClass('normal');$this.attr('data-added','true');fx.alertMessage("Theo dõi","Bạn đã theo dõi thành công phim này!",'success');}else{fx.alertMessage("Xin chào!","Bạn cần đăng nhập để sử dụng chức năng này!",'error');}}});};return false});});function onSearch($keysearch,$id){if($keysearch.length<1){$('.search-suggest').fadeOut();}else{$.post(MAIN_URL+'/ajax/suggest',{ajaxSearch:1,keysearch:$keysearch},function(data){if(data.length>0){$(".search-suggest").css({"display":"block"});$("#"+$id+" ul#search-suggest-list").html(data);}});}
return false;}
$(document).ready(function(){$(".navbar-notice-toggle").click(function(e){if(jQuery(".manage-notifi").hasClass("login-active"))
jQuery(".manage-notifi").removeClass("login-active");else
jQuery(".manage-notifi").addClass("login-active");e.stopPropagation();});$("div.navbar-notice").on('click','i#notification-delete',function(){var id=parseInt(jQuery(this).attr('data-id'));$.ajax({method:'POST',url:"/ajax/notification",data:{Delete:true,id:id},dataType:'json',success:function(data){if(data.status==1){loadNotif();}else{fx.alertMessage("Xin chào!","Bạn cần đăng nhập để sử dụng chức năng này!",'error');}}});});$("body").click(function(e){console.log(e.target.className);if(e.target.className=="notification-delete"||e.target.className=="fa-times"||e.target.className=="fa fa-times notification-delete"){console.log("Delete Notification");}else{jQuery(".manage-notifi").removeClass("login-active");}});loadNotif();});function getCookie(cname){var name=cname+"=";var ca=document.cookie.split(';');for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)==' ')c=c.substring(1);if(c.indexOf(name)!=-1){return c.substring(name.length,c.length);}}
return "";}
var filmInfo={};window.fbAsyncInit=function(){FB.init({appId:'1214104412028762',autoLogAppEvents:true,xfbml:true,version:'v2.12'});};(function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(d.getElementById(id)){return;}
js=d.createElement(s);js.id=id;js.async=true;js.src="https://connect.facebook.net/vi_VN/sdk.js";fjs.parentNode.insertBefore(js,fjs);}(document,'script','facebook-jssdk'));
